# Generated by Django 3.1 on 2020-08-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('image_url', models.URLField()),
                ('retail_price', models.IntegerField()),
                ('shoe', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref', models.BooleanField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('shoe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes1', to='api.sneaker')),
                ('shoe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes2', to='api.sneaker')),
            ],
        ),
    ]
