# Generated by Django 3.1 on 2020-08-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='loser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lost_votes', to='api.sneaker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='uid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='win_votes', to='api.sneaker'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('winner', 'loser', 'uid')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='pref',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='shoe1',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='shoe2',
        ),
    ]
